[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
time_locked_vault = "8wVnNuJttbSMP6zEMsCosBFb5UsdG4BgEjFa1iD9D2LM"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
